from django.contrib import admin
from . import models

admin.site.register(models.Nation)
admin.site.register(models.Company)
admin.site.register(models.Player)
admin.site.register(models.Territory)
admin.site.register(models.Building)
admin.site.register(models.PartialBuildingOwnership)
admin.site.register(models.BuildingEvaluation)
admin.site.register(models.BuildingEvaluationComponent)
admin.site.register(models.Denomination)
admin.site.register(models.Item)
admin.site.register(models.ItemCount)
admin.site.register(models.ItemFixedPriceComponent)
admin.site.register(models.ItemEvaluation)
admin.site.register(models.ItemEvaluationComponent)
admin.site.register(models.UserProfile)
admin.site.register(models.LiquidCount)
admin.site.register(models.LiquidAssetContainer)
admin.site.register(models.Liability)
admin.site.register(models.LiabilityPayment)
admin.site.register(models.CompanyShareholder)