# Generated by Django 5.2.1 on 2025-05-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('votes_for', models.PositiveIntegerField()),
                ('votes_against', models.PositiveIntegerField()),
                ('void', models.BooleanField(default=False)),
                ('repealed', models.BooleanField(default=False)),
            ],
        ),
    ]
