# Generated by Django 5.2.1 on 2025-05-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='body',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resolution',
            name='repealed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='void',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
