# Generated by Django 5.2.1 on 2025-05-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0002_resolution_body_alter_resolution_repealed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='body',
            field=models.TextField(),
        ),
    ]
