# Generated by Django 5.2.1 on 2025-05-22 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0059_rename_year_completed_building_year_started'),
        ('un_records_app', '0003_alter_resolution_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='proposed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proposed_resolution', to='un_app.nation'),
            preserve_default=False,
        ),
    ]
