# Generated by Django 5.2.1 on 2025-06-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0004_resolution_proposed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='invalidation_date',
            field=models.DateField(blank=True, default=None, help_text='Date the resolution was considered void or repealed', null=True),
        ),
    ]
