# Generated by Django 5.2.1 on 2025-06-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0059_rename_year_completed_building_year_started'),
        ('un_records_app', '0005_resolution_invalidation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treaty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField()),
                ('body', models.TextField()),
                ('void', models.BooleanField(blank=True, default=False)),
                ('invalidation_date', models.DateField(blank=True, default=None, help_text='Date the treaty was considered void', null=True)),
                ('nations_involved', models.ManyToManyField(related_name='treaty', to='un_app.nation')),
            ],
        ),
    ]
