# Generated by Django 5.2.1 on 2025-06-05 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0006_treaty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resolution_images/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which images should be displayed')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='un_records_app.resolution')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
