# Generated by Django 5.2.1 on 2025-06-11 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0059_rename_year_completed_building_year_started'),
        ('un_records_app', '0008_treatyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('charter', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('body', models.TextField()),
                ('void', models.BooleanField(blank=True, default=False)),
                ('repealed', models.BooleanField(blank=True, default=False)),
                ('invalidation_date', models.DateField(blank=True, default=None, help_text='Date the resolution was considered void or repealed', null=True)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_executive_order', to='un_app.nation')),
            ],
            options={
                'unique_together': {('number', 'charter')},
            },
        ),
    ]
