# Generated by Django 5.2.1 on 2025-06-11 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0059_rename_year_completed_building_year_started'),
        ('un_records_app', '0009_executive_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('votes_for', models.PositiveIntegerField()),
                ('votes_against', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('void', models.BooleanField(blank=True, default=False)),
                ('repealed', models.BooleanField(blank=True, default=False)),
                ('invalidation_date', models.DateField(blank=True, default=None, help_text='Date the amendment was considered void or repealed', null=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_amendment', to='un_app.nation')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amended_resolution', to='un_records_app.resolution')),
            ],
            options={
                'unique_together': {('number', 'resolution')},
            },
        ),
    ]
