# Generated by Django 5.2.1 on 2025-06-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0010_resolutionamendment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolutionamendment',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
