# Generated by Django 5.2.1 on 2025-06-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0011_alter_resolutionamendment_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('votes_for', models.PositiveIntegerField()),
                ('votes_against', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('void', models.BooleanField(blank=True, default=False)),
                ('repealed', models.BooleanField(blank=True, default=False)),
                ('invalidation_date', models.DateField(blank=True, default=None, help_text='Date the resolution was considered void or repealed', null=True)),
            ],
        ),
    ]
