# Generated by Django 5.2.1 on 2025-06-12 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0059_rename_year_completed_building_year_started'),
        ('un_records_app', '0012_charter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharterAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('votes_for', models.PositiveIntegerField()),
                ('votes_against', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('void', models.BooleanField(blank=True, default=False)),
                ('repealed', models.BooleanField(blank=True, default=False)),
                ('invalidation_date', models.DateField(blank=True, default=None, help_text='Date the amendment was considered void or repealed', null=True)),
                ('charter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendment_charter', to='un_records_app.charter')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charter_amendment', to='un_app.nation')),
            ],
            options={
                'unique_together': {('number', 'charter')},
            },
        ),
    ]
