# Generated by Django 5.2.1 on 2025-06-12 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0013_charteramendment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charteramendment',
            name='charter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amended_charter', to='un_records_app.charter'),
        ),
    ]
