# Generated by Django 5.2.1 on 2025-06-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0014_alter_charteramendment_charter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charteramendment',
            name='votes_against',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='charteramendment',
            name='votes_for',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
