# Generated by Django 5.2.1 on 2025-06-26 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0059_rename_year_completed_building_year_started'),
        ('un_records_app', '0015_alter_charteramendment_votes_against_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField()),
                ('body', models.TextField()),
                ('defunct', models.BooleanField(blank=True, default=False)),
                ('invalidation_date', models.DateField(blank=True, default=None, help_text='Date the alliance was considered defunct', null=True)),
                ('nations_involved', models.ManyToManyField(related_name='alliance', to='un_app.nation')),
            ],
        ),
        migrations.CreateModel(
            name='AllianceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='alliance_images/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which images should be displayed')),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='un_records_app.alliance')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
