# Generated by Django 5.2.1 on 2025-06-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0059_rename_year_completed_building_year_started'),
        ('un_records_app', '0016_alliance_allianceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration_Of_War',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField()),
                ('body', models.TextField()),
                ('resolved', models.BooleanField(blank=True, default=False)),
                ('peace_date', models.DateField(blank=True, default=None, help_text='Date the war was resolved', null=True)),
                ('nations_involved', models.ManyToManyField(related_name='declaration_of_war', to='un_app.nation')),
            ],
        ),
    ]
