# Generated by Django 5.2.1 on 2025-06-26 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0017_declaration_of_war'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration_of_war',
            name='resolving_treaty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolving_treaty', to='un_records_app.treaty'),
        ),
    ]
