# Generated by Django 5.2.1 on 2025-06-28 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0059_rename_year_completed_building_year_started'),
        ('un_records_app', '0019_rename_allianceimage_alliance_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alliance_Image',
            new_name='AllianceImage',
        ),
        migrations.RenameModel(
            old_name='Charter_Amendment',
            new_name='CharterAmendment',
        ),
        migrations.RenameModel(
            old_name='Declaration_Of_War',
            new_name='DeclarationOfWar',
        ),
        migrations.RenameModel(
            old_name='Executive_Order',
            new_name='ExecutiveOrder',
        ),
        migrations.RenameModel(
            old_name='National_Constitution',
            new_name='NationalConstitution',
        ),
        migrations.RenameModel(
            old_name='National_Constitution_Amendment',
            new_name='NationalConstitutionAmendment',
        ),
        migrations.RenameModel(
            old_name='Resolution_Amendment',
            new_name='ResolutionAmendment',
        ),
        migrations.RenameModel(
            old_name='Resolution_Image',
            new_name='ResolutionImage',
        ),
        migrations.RenameModel(
            old_name='Treaty_Image',
            new_name='TreatyImage',
        ),
        migrations.CreateModel(
            name='CourtCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField()),
                ('votes_innocent', models.PositiveIntegerField()),
                ('votes_guilty', models.PositiveIntegerField()),
                ('ruling_body', models.TextField()),
                ('defendant_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defendant_company', to='un_app.company')),
                ('defendant_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defendant_individual', to='un_app.player')),
                ('defendant_nation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defendant_nation', to='un_app.nation')),
                ('plaintiff_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plaintiff_company', to='un_app.company')),
                ('plaintiff_individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plaintiff_individual', to='un_app.player')),
                ('plaintiff_nation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plaintiff_nation', to='un_app.nation')),
            ],
        ),
    ]
