# Generated by Django 5.2.1 on 2025-06-28 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0059_rename_year_completed_building_year_started'),
        ('un_records_app', '0020_rename_alliance_image_allianceimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtCaseArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('argument_type', models.CharField(choices=[('Plaintiff Argument', 'Plaintiff Argument'), ('Defendant Argument', 'Defendant Argument'), ('Concurring Opinion', 'Concurring Opinion'), ('Dissenting Opinion', 'Dissenting Opinion'), ('Witness Direct Examination', 'Witness Direct Examination'), ('Witness Cross Examination', 'Witness Cross Examination')], max_length=50)),
                ('body', models.TextField()),
                ('court_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_argued', to='un_records_app.courtcase')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_amendment', to='un_app.player')),
            ],
            options={
                'unique_together': {('number', 'court_case')},
            },
        ),
        migrations.CreateModel(
            name='CourtCaseArgumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='court_case_images/')),
                ('evidence_letter', models.CharField(max_length=1)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which images should be displayed')),
                ('court_case_argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='un_records_app.courtcaseargument')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
