# Generated by Django 5.2.1 on 2025-06-29 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0021_courtcaseargument_courtcaseargumentimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courtcase',
            old_name='votes_guilty',
            new_name='votes_for_defendant',
        ),
        migrations.RenameField(
            model_name='courtcase',
            old_name='votes_innocent',
            new_name='votes_for_plaintiff',
        ),
    ]
