# Generated by Django 5.2.1 on 2025-07-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0059_rename_year_completed_building_year_started'),
        ('un_records_app', '0022_rename_votes_guilty_courtcase_votes_for_defendant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alliance',
            old_name='nations_involved',
            new_name='member_nations',
        ),
        migrations.AddField(
            model_name='alliance',
            name='partial_member_nations',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='partial_alliance', to='un_app.nation'),
        ),
    ]
