# Generated by Django 5.2.1 on 2025-07-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0023_rename_nations_involved_alliance_member_nations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalconstitution',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
