# Generated by Django 5.2.1 on 2025-07-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0024_nationalconstitution_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtcaseargument',
            name='argument_type',
            field=models.CharField(choices=[('Plaintiff Argument', 'Plaintiff Argument'), ('Defendant Argument', 'Defendant Argument'), ('Concurring Opinion', 'Concurring Opinion'), ('Dissenting Opinion', 'Dissenting Opinion'), ('Witness Direct Examination', 'Witness Direct Examination'), ('Witness Cross Examination', 'Witness Cross Examination'), ('War Crime Tribunal', 'War Crime Tribunal')], max_length=50),
        ),
    ]
