# Generated by Django 5.2.4 on 2025-07-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0026_alter_courtcase_votes_for_defendant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtcase',
            name='votes_for_defendant',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courtcase',
            name='votes_for_plaintiff',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
