# Generated by Django 5.2.4 on 2025-07-09 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0059_rename_year_completed_building_year_started'),
        ('un_records_app', '0027_alter_courtcase_votes_for_defendant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtcaseargument',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolution_amendment', to='un_app.player'),
        ),
    ]
