# Generated by Django 5.2.4 on 2025-07-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0059_rename_year_completed_building_year_started'),
        ('un_records_app', '0028_alter_courtcaseargument_speaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtcase',
            name='defendant_company',
        ),
        migrations.RemoveField(
            model_name='courtcase',
            name='defendant_individual',
        ),
        migrations.RemoveField(
            model_name='courtcase',
            name='defendant_nation',
        ),
        migrations.RemoveField(
            model_name='courtcase',
            name='plaintiff_company',
        ),
        migrations.RemoveField(
            model_name='courtcase',
            name='plaintiff_individual',
        ),
        migrations.RemoveField(
            model_name='courtcase',
            name='plaintiff_nation',
        ),
        migrations.AddField(
            model_name='courtcase',
            name='defendant_company',
            field=models.ManyToManyField(blank=True, related_name='defendant_company', to='un_app.company'),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='defendant_individual',
            field=models.ManyToManyField(blank=True, related_name='defendant_individual', to='un_app.player'),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='defendant_nation',
            field=models.ManyToManyField(blank=True, related_name='defendant_nation', to='un_app.nation'),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='plaintiff_company',
            field=models.ManyToManyField(blank=True, related_name='plaintiff_company', to='un_app.company'),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='plaintiff_individual',
            field=models.ManyToManyField(blank=True, related_name='plaintiff_individual', to='un_app.player'),
        ),
        migrations.AddField(
            model_name='courtcase',
            name='plaintiff_nation',
            field=models.ManyToManyField(blank=True, related_name='plaintiff_nation', to='un_app.nation'),
        ),
    ]
