# Generated by Django 5.2.4 on 2025-07-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0029_remove_courtcase_defendant_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtcase',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
