# Generated by Django 5.2.4 on 2025-07-11 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0031_courtcaseargumentimage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtCaseArgumentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField()),
                ('evidence_letter', models.CharField(max_length=1)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which videos should be displayed')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('court_case_argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='un_records_app.courtcaseargument')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
