# Generated by Django 5.2.4 on 2025-07-16 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0059_rename_year_completed_building_year_started'),
        ('un_records_app', '0032_courtcaseargumentvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField()),
                ('petition_type', models.CharField(choices=[('Petition to Build into Maritime Territory', 'Petition to Build into Maritime Territory'), ('Motion to Enter Buildings into the Register of Historic and Cultural Structures', 'Motion to Enter Buildings into the Register of Historic and Cultural Structures'), ('Motion for Admission into the United Nations', 'otion for Admission into the United Nations')], max_length=100)),
                ('body', models.TextField()),
                ('petitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petitioner_nation', to='un_app.nation')),
            ],
        ),
        migrations.CreateModel(
            name='PetitionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='petition_images/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which images should be displayed')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='un_records_app.petition')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
