# Generated by Django 5.2.4 on 2025-07-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0033_petition_petitionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='votes_against',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petition',
            name='votes_for',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='petition',
            name='petition_type',
            field=models.CharField(choices=[('Petition to Build into Maritime Territory', 'Petition to Build into Maritime Territory'), ('Motion to Enter Buildings into the Register of Historic and Cultural Structures', 'Motion to Enter Buildings into the Register of Historic and Cultural Structures'), ('Motion for Admission into the United Nations', 'Motion for Admission into the United Nations')], max_length=100),
        ),
    ]
