# Generated by Django 5.2.4 on 2025-10-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0061_remove_item_description_item_note'),
        ('un_records_app', '0034_petition_votes_against_petition_votes_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alliance',
            name='partial_member_nations',
            field=models.ManyToManyField(blank=True, default=None, related_name='partial_alliance', to='un_app.nation'),
        ),
    ]
