# Generated by Django 5.2.7 on 2025-12-06 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0069_alter_item_image_name_alter_item_special_image_name'),
        ('un_records_app', '0035_alter_alliance_partial_member_nations'),
    ]

    operations = [
        migrations.CreateModel(
            name='AternosGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('participating_nations', models.ManyToManyField(blank=True, related_name='aternos_game', to='un_app.nation')),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('POINTS', 'Archery / Points'), ('TIME', 'Boat Racing / Timed'), ('TOURNAMENT', 'Gladiator / Tournament')], max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='un_records_app.aternosgame')),
            ],
        ),
        migrations.CreateModel(
            name='EventStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='un_records_app.gameevent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('final_placement', models.PositiveIntegerField(blank=True, null=True)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='un_app.nation')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='un_records_app.gameevent')),
            ],
            options={
                'unique_together': {('event', 'nation')},
            },
        ),
        migrations.CreateModel(
            name='PointResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('disqualified', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_results', to='un_records_app.eventparticipation')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_results', to='un_records_app.eventstage')),
            ],
        ),
        migrations.CreateModel(
            name='TimeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_seconds', models.FloatField()),
                ('disqualified', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_results', to='un_records_app.eventparticipation')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_results', to='un_records_app.eventstage')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminated', models.BooleanField(default=False)),
                ('disqualified', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_results', to='un_records_app.eventparticipation')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_round_results', to='un_records_app.eventstage')),
            ],
        ),
    ]
