# Generated by Django 5.2.7 on 2025-12-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0036_aternosgame_gameevent_eventstage_eventparticipation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentroundresult',
            options={'ordering': ['matchup_number', 'id']},
        ),
        migrations.AddField(
            model_name='tournamentroundresult',
            name='matchup_number',
            field=models.PositiveIntegerField(default=1, help_text='Which matchup in this stage (1, 2, 3, etc.)'),
        ),
        migrations.AlterField(
            model_name='gameevent',
            name='event_type',
            field=models.CharField(choices=[('POINTS', 'Points'), ('TIME', 'Timed'), ('TOURNAMENT', 'Tournament')], max_length=20),
        ),
    ]
