# Generated by Django 5.2.7 on 2025-12-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0037_alter_tournamentroundresult_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentroundresult',
            name='matchup_number',
            field=models.PositiveIntegerField(default=0, help_text='Which matchup in this stage (1, 2, 3, etc.)'),
        ),
    ]
