# Generated by Django 5.2.7 on 2026-02-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0038_alter_tournamentroundresult_matchup_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255),
        ),
    ]
