# Generated by Django 5.2.7 on 2026-02-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0040_auto_20260208_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
