# Generated by Django 5.2.11 on 2026-02-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0041_alter_resolution_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='treaty',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255),
        ),
    ]
