# Generated by Django 5.2.11 on 2026-02-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0043_auto_20260208_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treaty',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
