# Generated by Django 5.2.11 on 2026-02-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_records_app', '0046_auto_20260208_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtcase',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
