# Generated by Django 5.2 on 2025-04-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_type_id', models.IntegerField()),
                ('slot', models.IntegerField()),
                ('item_id', models.TextField()),
                ('amount', models.IntegerField()),
                ('name', models.TextField()),
                ('custom_name', models.TextField(blank=True, null=True)),
                ('enchantments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Players_Online',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
            ],
            options={
                'db_table': 'players_online',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.TextField()),
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('skin_data', models.TextField(blank=True, null=True)),
                ('skin_sig', models.TextField(blank=True, null=True)),
                ('skin_image', models.BinaryField(blank=True, null=True)),
                ('face_image', models.BinaryField(blank=True, null=True)),
                ('is_slim', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
