# Generated by Django 5.2.11 on 2026-03-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartographyMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('map_date', models.DateField(db_index=True)),
                ('type', models.TextField(blank=True)),
                ('map_a', models.ImageField(upload_to='cartography/maps/')),
                ('map_b', models.ImageField(blank=True, null=True, upload_to='cartography/maps/')),
                ('map_c', models.ImageField(blank=True, null=True, upload_to='cartography/maps/')),
                ('map_d', models.ImageField(blank=True, null=True, upload_to='cartography/maps/')),
                ('map_e', models.ImageField(blank=True, null=True, upload_to='cartography/maps/')),
            ],
            options={
                'verbose_name': 'Cartography Map',
                'verbose_name_plural': 'Cartography Commission Maps',
                'ordering': ['-map_date'],
            },
        ),
    ]
