# Generated by Django 5.2.11 on 2026-03-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartographymap',
            options={},
        ),
        migrations.AddField(
            model_name='cartographymap',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cartographymap',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
