# Generated by Django 5.2.11 on 2026-03-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography_app', '0002_alter_cartographymap_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartographymap',
            name='type',
            field=models.CharField(choices=[('Eligible', 'Eligible'), ('Nominated', 'Nominated'), ('Won', 'Won')], max_length=100),
        ),
    ]
