# Generated by Django 5.2.11 on 2026-03-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography_app', '0003_alter_cartographymap_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartographymap',
            name='type',
            field=models.CharField(choices=[('Official', 'Official UN Map'), ('Territory', 'UN Territory Map'), ('Infastructure', 'Infastructure Map'), ('Evaluation', 'Evaluation Map')], max_length=100),
        ),
    ]
