# Generated by Django 5.2.11 on 2026-03-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography_app', '0004_alter_cartographymap_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartographymap',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cartographymap',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cartographymap',
            name='type',
            field=models.CharField(choices=[('Official', 'Official UN Map'), ('Territory', 'UN Territory Map'), ('Infrastructure', 'Infrastructure Map'), ('Evaluation', 'Evaluation Map')], max_length=100),
        ),
    ]
