# Generated by Django 5.2.11 on 2026-03-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography_app', '0005_alter_cartographymap_slug_alter_cartographymap_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartographymap',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
