# Generated by Django 5.2.11 on 2026-03-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography_app', '0006_alter_cartographymap_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartographymap',
            name='changes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cartographymap',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cartographymap',
            name='type',
            field=models.CharField(choices=[('Official', 'Official UN Map'), ('FarColony', 'Official UN Far Colonies Map'), ('Territory', 'UN Territory Map'), ('Infrastructure', 'Infrastructure Map'), ('Evaluation', 'Evaluation Map')], max_length=100),
        ),
    ]
