# Generated by Django 5.2.11 on 2026-03-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography_app', '0007_cartographymap_changes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartographymap',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
