# Generated by Django 5.2.16 on 2026-07-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartography_app', '0008_alter_cartographymap_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartographymap',
            name='type',
            field=models.CharField(choices=[('Official', 'Official UN Map'), ('FarColony', 'Official UN Far Colonies Map'), ('Unofficial', 'Unofficial UN Map'), ('Territory', 'UN Territory Map'), ('Infrastructure', 'Infrastructure Map'), ('Evaluation', 'Evaluation Map')], max_length=100),
        ),
    ]
