"""
Django settings for un_project project.

Generated by 'django-admin startproject' using Django 2.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xx7av6y(1gj3gu(3ro0-=s5^8r@8o=bt0t9_q!y15_rkma%%lh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['ws-studios.com', 'werespecialstudios.com', 'www.ws-studios.com', 'www.werespecialstudios.com', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',   # Django REST Framework for API functionality
    'un_app',           # Your main app containing the financial models and stuff
    'un_records_app',   # used for records stuff like resolutions
    'un_api',           # New app for API views
    'website',          # Main website app
    'players_api',
    'corsheaders',      # CORS headers for api and login usage
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CORS_ALLOWED_ORIGINS = [
    'https://ws-studios.com',
    'https://werespecialstudios.com',
    'https://www.ws-studios.com',
    'https://www.werespecialstudios.com',
]

CSRF_TRUSTED_ORIGINS = [
    'https://ws-studios.com',
    'https://werespecialstudios.com',
    'https://www.ws-studios.com',
    'https://www.werespecialstudios.com',
]

ROOT_URLCONF = 'un_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'un_app.context_processors.nations_and_companies',
            ],
        },
    },
]

WSGI_APPLICATION = 'un_project.wsgi.application'


# Makes te api view only return as json data
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'united_nations_db',
        'USER': 'un_project_user',
        'PASSWORD': 'passtheword',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'players': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'players',
        'USER': 'website',
        'PASSWORD': 'Bl0ckG@me',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

DATABASE_ROUTERS = ['un_project.player_routers.PlayersRouter']


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


LOGIN_URL = 'login'  # URL name for the login page
LOGIN_REDIRECT_URL = 'evaluate_buildings'  # Redirect after successful login
LOGOUT_REDIRECT_URL = 'login'  # Redirect after logout

