# Generated by Django 5.1 on 2024-08-24 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('un_rep', models.BooleanField(default=False)),
                ('temp_field', models.CharField(blank=True, max_length=10, null=True)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='un_app.nation')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('y_level_high_pt', models.FloatField()),
                ('y_level_ground', models.FloatField()),
                ('height', models.FloatField()),
                ('year_completed', models.IntegerField()),
                ('coordinates', models.CharField(max_length=50)),
                ('historic_site', models.BooleanField(default=False)),
                ('architectural_genius', models.BooleanField(default=False)),
                ('moPQ_award', models.BooleanField(default=False)),
                ('architectural_style', models.CharField(blank=True, max_length=100, null=True)),
                ('y_level_lowest', models.FloatField(blank=True, null=True)),
                ('height_below_ground', models.FloatField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_buildings', to='un_app.nation')),
                ('main_builder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_builds', to='un_app.player')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='un_app.territory')),
            ],
        ),
    ]
