# Generated by Django 5.1.1 on 2024-09-30 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="height",
        ),
        migrations.RemoveField(
            model_name="building",
            name="height_below_ground",
        ),
        migrations.RemoveField(
            model_name="building",
            name="y_level_lowest",
        ),
    ]
