# Generated by Django 5.1.1 on 2024-09-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0002_remove_building_height_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="coordinates",
        ),
        migrations.RemoveField(
            model_name="player",
            name="temp_field",
        ),
        migrations.AddField(
            model_name="building",
            name="x_coordinate",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="building",
            name="z_coordinate",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
