# Generated by Django 5.1.1 on 2024-10-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "un_app",
            "0003_remove_building_coordinates_remove_player_temp_field_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="completed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="moPQ_award",
            field=models.BooleanField(null=True),
        ),
    ]
