# Generated by Django 5.1.1 on 2024-10-01 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0004_building_completed_alter_building_mopq_award"),
    ]

    operations = [
        migrations.RenameField(
            model_name="building",
            old_name="moPQ_award",
            new_name="mopq_award",
        ),
    ]
