# Generated by Django 5.1.1 on 2024-10-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0005_rename_mopq_award_building_mopq_award"),
    ]

    operations = [
        migrations.AddField(
            model_name="nation",
            name="abbreviation",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
