# Generated by Django 5.1.1 on 2024-10-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0006_nation_abbreviation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="nation",
            name="abbreviation",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="nation",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="territory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
