# Generated by Django 5.1.1 on 2024-10-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0007_alter_building_name_alter_nation_abbreviation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="mopq_award",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
