# Generated by Django 5.1.1 on 2024-10-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0009_remove_building_main_builder_building_main_builders_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="y_level_ground",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="building",
            name="y_level_high_pt",
            field=models.FloatField(null=True),
        ),
    ]
