# Generated by Django 5.1.1 on 2024-10-02 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0011_alter_building_year_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="territory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings",
                to="un_app.territory",
            ),
        ),
    ]
