# Generated by Django 5.1.1 on 2024-10-03 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("un_app", "0013_company_buildingownership"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartialBuildingOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partial_owner_abbreviation", models.PositiveIntegerField()),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="un_app.building",
                    ),
                ),
                (
                    "partial_owner_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("building", "partial_owner_type", "partial_owner_abbreviation")
                },
            },
        ),
        migrations.DeleteModel(
            name="BuildingOwnership",
        ),
    ]
