# Generated by Django 5.1.1 on 2024-10-03 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("un_app", "0014_partialbuildingownership_delete_buildingownership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partialbuildingownership",
            name="partial_owner_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ("nation", "company")},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
