# Generated by Django 5.1.1 on 2024-10-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0015_alter_partialbuildingownership_partial_owner_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partialbuildingownership",
            name="partial_owner_abbreviation",
            field=models.CharField(max_length=100),
        ),
    ]
