# Generated by Django 5.1.1 on 2024-10-04 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0017_alter_partialbuildingownership_percentage"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluation_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("evaluation_date", models.DateField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="un_app.building",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="un_app.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("building", "evaluator")},
            },
        ),
    ]
