# Generated by Django 5.1.1 on 2024-10-07 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0019_alter_buildingevaluation_evaluation_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price_type",
                    models.CharField(
                        choices=[("fixed", "Fixed Price"), ("market", "Market Rate")],
                        max_length=10,
                    ),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="buildingevaluation",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="building_evaluations",
                to="un_app.building",
            ),
        ),
        migrations.AlterField(
            model_name="buildingevaluation",
            name="evaluator",
            field=models.ForeignKey(
                limit_choices_to={"un_rep": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="building_evaluations",
                to="un_app.player",
            ),
        ),
        migrations.CreateModel(
            name="ItemCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="un_app.item"
                    ),
                ),
                (
                    "nation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="un_app.nation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=10, max_digits=20)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluator",
                    models.ForeignKey(
                        limit_choices_to={"un_rep": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="un_app.player",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        limit_choices_to={"price_type": "market"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_evaluations",
                        to="un_app.item",
                    ),
                ),
            ],
        ),
    ]
