# Generated by Django 5.1.1 on 2024-10-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "un_app",
            "0021_item_description_alter_building_architectural_genius_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="mopq_award",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Eligible", "Eligible"),
                    ("Nominated", "Nominated"),
                    ("Won", "Won"),
                ],
                help_text="Medal of Papa Quinn (MoPQ) award for architecture or another MoPQ award related to a building.",
                max_length=50,
                null=True,
            ),
        ),
    ]
