# Generated by Django 5.1.1 on 2024-10-09 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0022_alter_building_mopq_award"),
    ]

    operations = [
        migrations.CreateModel(
            name="Denomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "diamond_equivalent",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="item",
            name="fixed_price",
        ),
        migrations.RemoveField(
            model_name="itemevaluation",
            name="value",
        ),
        migrations.CreateModel(
            name="ItemEvaluationComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "denomination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="un_app.denomination",
                    ),
                ),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_components",
                        to="un_app.itemevaluation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemPriceComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "denomination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="un_app.denomination",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_components",
                        to="un_app.item",
                    ),
                ),
            ],
        ),
    ]
