# Generated by Django 5.1.1 on 2024-10-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0023_denomination_remove_item_fixed_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denomination",
            name="diamond_equivalent",
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
