# Generated by Django 5.1.1 on 2024-10-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0025_remove_buildingevaluation_evaluation_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
