# Generated by Django 5.1.1 on 2024-10-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0028_alter_player_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="username",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
