# Generated by Django 5.1.1 on 2024-10-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0030_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="denomination",
            name="priority",
            field=models.IntegerField(null=True),
        ),
    ]
