# Generated by Django 5.1.1 on 2024-10-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0031_denomination_priority"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ItemPriceComponent",
            new_name="ItemFixedPriceComponent",
        ),
    ]
