# Generated by Django 5.1.1 on 2024-10-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0032_rename_itempricecomponent_itemfixedpricecomponent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="itemcount",
            unique_together={("nation", "item")},
        ),
        migrations.AlterUniqueTogether(
            name="itemfixedpricecomponent",
            unique_together={("item",)},
        ),
    ]
