# Generated by Django 5.1.1 on 2024-10-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0033_alter_item_name_alter_itemcount_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="ordering",
            field=models.IntegerField(default=0),
        ),
    ]
