# Generated by Django 5.1.1 on 2024-10-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0034_item_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price_type",
            field=models.CharField(
                choices=[("fixed", "Fixed Price"), ("market", "Market Rate")],
                max_length=12,
            ),
        ),
    ]
