# Generated by Django 5.1.1 on 2024-10-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0035_alter_item_price_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed Price"),
                    ("market", "Market Rate"),
                    ("section_divider", "Section Divider"),
                ],
                max_length=15,
            ),
        ),
    ]
