# Generated by Django 5.1.1 on 2024-10-16 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0036_alter_item_price_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price_type",
            field=models.CharField(
                choices=[
                    ("fixed_price", "Fixed Price"),
                    ("market_rate", "Market Rate"),
                    ("section_divider", "Section Divider"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="itemevaluation",
            name="item",
            field=models.ForeignKey(
                limit_choices_to={"price_type": "market_rate"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_evaluations",
                to="un_app.item",
            ),
        ),
    ]
