# Generated by Django 5.1.1 on 2024-10-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0039_alter_itemfixedpricecomponent_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemfixedpricecomponent",
            name="percentage_of_item",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Percentage of the referenced item's price to use (Ex: 50 = 50%)",
                max_digits=20,
                null=True,
            ),
        ),
    ]
