# Generated by Django 5.1.1 on 2024-10-21 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0040_alter_itemfixedpricecomponent_percentage_of_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquidCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_name", models.CharField(max_length=100)),
                ("count", models.DecimalField(decimal_places=3, max_digits=20)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="un_app.company",
                    ),
                ),
                (
                    "denomination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="un_app.denomination",
                    ),
                ),
                (
                    "nation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="un_app.nation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nation", "asset_name"), name="unique_nation_asset"
                    ),
                    models.UniqueConstraint(
                        fields=("company", "asset_name"), name="unique_company_asset"
                    ),
                    models.UniqueConstraint(
                        fields=("asset_name", "denomination"),
                        name="unique_asset_denomination",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("company__isnull", True), ("nation__isnull", False)
                            ),
                            models.Q(
                                ("company__isnull", False), ("nation__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="nation_or_company_liquid_not_both",
                    ),
                ],
            },
        ),
    ]
