# Generated by Django 5.1.1 on 2024-10-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0041_liquidcount"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="liquidcount",
            name="unique_nation_asset",
        ),
        migrations.RemoveConstraint(
            model_name="liquidcount",
            name="unique_company_asset",
        ),
        migrations.AddConstraint(
            model_name="liquidcount",
            constraint=models.UniqueConstraint(
                fields=("nation", "asset_name", "denomination"),
                name="unique_nation_asset_denomination",
            ),
        ),
        migrations.AddConstraint(
            model_name="liquidcount",
            constraint=models.UniqueConstraint(
                fields=("company", "asset_name", "denomination"),
                name="unique_company_asset",
            ),
        ),
    ]
