# Generated by Django 5.1.1 on 2024-10-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0042_remove_liquidcount_unique_nation_asset_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="liquidcount",
            name="unique_nation_asset_denomination",
        ),
        migrations.RemoveConstraint(
            model_name="liquidcount",
            name="unique_company_asset",
        ),
    ]
