# Generated by Django 5.1.1 on 2024-11-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0043_remove_liquidcount_unique_nation_asset_denomination_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="liquidcount",
            name="unique_asset_denomination",
        ),
        migrations.AddConstraint(
            model_name="liquidcount",
            constraint=models.UniqueConstraint(
                fields=("nation", "asset_name", "denomination"),
                name="unique_nation_asset_denomination",
            ),
        ),
        migrations.AddConstraint(
            model_name="liquidcount",
            constraint=models.UniqueConstraint(
                fields=("company", "asset_name", "denomination"),
                name="unique_company_asset",
            ),
        ),
    ]
