# Generated by Django 5.1.1 on 2024-11-07 18:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0044_remove_liquidcount_unique_asset_denomination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="market_value",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0"), max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="itemcount",
            name="total_value",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0"), max_digits=20
            ),
        ),
    ]
