# Generated by Django 5.1.1 on 2024-11-07 23:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0045_item_market_value_itemcount_total_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="ownership_minus_partial",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="building",
            name="price_minus_partial",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0"), max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="partialbuildingownership",
            name="partial_price",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0"), max_digits=20
            ),
        ),
    ]
