# Generated by Django 5.1.1 on 2024-11-11 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0049_liquidassetcontainer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquidcount",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="un_app.company",
            ),
        ),
        migrations.AddField(
            model_name="liquidcount",
            name="nation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="un_app.nation",
            ),
        ),
    ]
