# Generated by Django 5.1.1 on 2024-11-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0050_liquidcount_company_liquidcount_nation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liquidcount",
            name="company",
        ),
        migrations.RemoveField(
            model_name="liquidcount",
            name="nation",
        ),
    ]
