# Generated by Django 5.1.1 on 2024-11-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0051_remove_liquidcount_company_remove_liquidcount_nation"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="liquidcount",
            constraint=models.UniqueConstraint(
                fields=("asset_container", "denomination"),
                name="unique_asset_denomination",
            ),
        ),
    ]
