# Generated by Django 5.1.1 on 2024-11-16 14:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("un_app", "0052_liquidcount_unique_asset_denomination"),
    ]

    operations = [
        migrations.CreateModel(
            name="Liability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debtor_abbreviation", models.CharField(max_length=100)),
                ("creditor_abbreviation", models.CharField(max_length=100)),
                (
                    "liability_type",
                    models.CharField(
                        choices=[
                            ("loan", "Loan"),
                            ("mortgage", "Mortgage"),
                            ("fine", "Fine"),
                            ("promise", "Promise of Payment"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("creation_date", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "total_diamond_value",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "remaining_diamond_value",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "creditor_type",
                    models.ForeignKey(
                        help_text="The entity that is owed the liability",
                        limit_choices_to={"model__in": ("nation", "company")},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creditor_liabilities",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "debtor_type",
                    models.ForeignKey(
                        help_text="The entity that owes the liability",
                        limit_choices_to={"model__in": ("nation", "company")},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debtor_liabilities",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiabilityPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "diamond_amount",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                (
                    "liability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="un_app.liability",
                    ),
                ),
            ],
        ),
    ]
