# Generated by Django 5.1.1 on 2024-11-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0053_liability_liabilitypayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="liabilitypayment",
            name="payment_number",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
