# Generated by Django 5.1.1 on 2024-11-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("un_app", "0054_liabilitypayment_payment_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liabilitypayment",
            name="payment_number",
            field=models.IntegerField(default=1),
        ),
    ]
