# Generated by Django 5.1.1 on 2024-12-06 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("un_app", "0056_alter_liabilitypayment_payment_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyShareholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shareholder_abbreviation", models.CharField(max_length=100)),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage ownership of the company",
                        max_digits=5,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shareholders",
                        to="un_app.company",
                    ),
                ),
                (
                    "shareholder_type",
                    models.ForeignKey(
                        help_text="The type of entity that owns shares (Nation or Company)",
                        limit_choices_to={"model__in": ("nation", "company")},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-percentage"],
                "unique_together": {
                    ("company", "shareholder_type", "shareholder_abbreviation")
                },
            },
        ),
    ]
