# Generated by Django 5.2 on 2025-04-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0057_companyshareholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='furnished',
            field=models.BooleanField(blank=True, help_text='Whether the building is furnished inside', null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='materials',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic (Dirt, Cobblestone, Netherrack, Oak Planks...)'), ('Standard', 'Standard (Stone Bricks, Smooth Sandstone, Terracotta...)'), ('Premium', 'Premium (Smooth Stone, glazed terricotta, exotic woods and stones...)'), ('Elite', 'Elite (Quartz, Obsidian, Purpur, Prismarine...)')], help_text='The primary building materials used in construction', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='size',
            field=models.CharField(blank=True, choices=[('Tiny', 'Tiny (-5×5)'), ('Very Small', 'Very Small (6×6 to 8×8)'), ('Small', 'Small (9×9 to 12×12)'), ('Modest', 'Modest (12×12 to 15×15)'), ('Medium-Small', 'Medium-Small (16×16 to 20×20)'), ('Medium', 'Medium (20×20 to 25×25)'), ('Medium-Large', 'Medium-Large (25×25 to 30×30)'), ('Large', 'Large (31×31 to 40×40)'), ('Very Large', 'Very Large (40×40 to 50×50)'), ('Huge', 'Huge (51×51 to 75×75)'), ('Enormous', 'Enormous (75×75 to 100×100)'), ('Gigantic', 'Gigantic (100×100 to 150×150)'), ('Massive', 'Massive (150×150+)')], help_text='The size category of the building', max_length=20, null=True),
        ),
    ]
