# Generated by Django 5.2 on 2025-05-08 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0058_building_furnished_building_materials_building_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='year_completed',
            new_name='year_started',
        ),
    ]
