# Generated by Django 5.2.4 on 2025-09-05 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0059_rename_year_completed_building_year_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyshareholder',
            name='board_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='un_app.player'),
        ),
    ]
