# Generated by Django 5.2.4 on 2025-10-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0060_companyshareholder_board_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.CharField(blank=True, help_text='Used for short note about an oddity with the item', max_length=255),
        ),
    ]
