# Generated by Django 5.2.4 on 2025-10-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0061_remove_item_description_item_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True),
        ),
    ]
