# Generated by Django 5.2.4 on 2025-10-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0062_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
