# Generated by Django 5.2.4 on 2025-10-05 06:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0063_item_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_assets', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('liquid_assets', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('item_assets', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('building_assets', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('other_assets', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='un_app.nation')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
