# Generated by Django 5.2.4 on 2025-10-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0064_nationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationhistory',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
