# Generated by Django 5.2.4 on 2025-10-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0065_alter_nationhistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationhistory',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
