# Generated by Django 5.2.4 on 2025-10-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0065_alter_nationhistory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.CharField(blank=True, help_text='Used for short note about an oddity with the item', max_length=255),
        ),
    ]
