# Generated by Django 5.2.4 on 2025-10-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0066_nationhistory_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationhistory',
            name='building_assets',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='nationhistory',
            name='item_assets',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='nationhistory',
            name='liquid_assets',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='nationhistory',
            name='other_assets',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='nationhistory',
            name='total_assets',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
