# Generated by Django 5.2.4 on 2025-10-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0067_alter_nationhistory_building_assets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='special_image_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
