# Generated by Django 5.2.4 on 2025-10-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0068_item_special_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_name',
            field=models.CharField(blank=True, help_text='Image name and used for Minecraft Wiki link', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='special_image_name',
            field=models.CharField(blank=True, help_text='Overrided image_name for the image, use for when the wiki link does not match the image name', max_length=255),
        ),
    ]
