# Generated by Django 5.2.11 on 2026-02-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0069_alter_item_image_name_alter_item_special_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='destroyed',
            field=models.BooleanField(default=False, help_text='Whether the building has been destroyed'),
        ),
        migrations.AddField(
            model_name='building',
            name='year_destroyed',
            field=models.IntegerField(blank=True, help_text='The year the building was destroyed', null=True),
        ),
    ]
