# Generated by Django 5.2.16 on 2026-07-08 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_app', '0070_building_destroyed_building_year_destroyed'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='headquarters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headquarters', to='un_app.building'),
        ),
        migrations.AddField(
            model_name='company',
            name='headquarters_unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='building',
            name='main_builders',
            field=models.ManyToManyField(blank=True, help_text='The builder/builders who constructed the majority of the building', related_name='main_builds', to='un_app.player'),
        ),
        migrations.AlterField(
            model_name='building',
            name='size',
            field=models.CharField(blank=True, choices=[('Tiny', 'Tiny (5×5 and smaller)'), ('Very Small', 'Very Small (6×6 to 8×8)'), ('Small', 'Small (9×9 to 12×12)'), ('Modest', 'Modest (13×13 to 15×15)'), ('Medium-Small', 'Medium-Small (16×16 to 20×20)'), ('Medium', 'Medium (21×21 to 25×25)'), ('Medium-Large', 'Medium-Large (26×26 to 30×30)'), ('Large', 'Large (31×31 to 40×40)'), ('Very Large', 'Very Large (41×41 to 50×50)'), ('Huge', 'Huge (51×51 to 75×75)'), ('Enormous', 'Enormous (76×76 to 100×100)'), ('Gigantic', 'Gigantic (101×101 to 150×150)'), ('Massive', 'Massive (151×151 and larger)')], help_text='The size category of the building', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='territory',
            field=models.ForeignKey(blank=True, help_text='The name of the territory district that this building resides. This does not necessarily indicate owner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='un_app.territory'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('headquarters', 'headquarters_unit'), name='unique_company_headquarters_unit'),
        ),
    ]
